const SITE = {
  name: "Zosia Marciniak",
  formalName: "Zofia Marciniak",
  pronounciation: "Zoh-see-ah",
  title: "PhD student at ETH Zurich",
  tagline: "human–computer interaction · crafting technology",
  bio: `My name is Zofia (formally), or Zosia (pronounced Zoh-see-ah, or 조시아).<br> I am a PhD student in Computer Science at ETH Zurich, advised by <a href="http://aprilwang.me" target="_blank" rel="noopener" class="text-link">Prof. April Wang</a> in the <a href="http://peachlab.inf.ethz.ch" target="_blank" rel="noopener" class="text-link">PEACH Lab</a>. Previously, I worked as an Engineer at Samsung Electronics and completed my master's degree at <a href="http://make.kaist.ac.kr" target="_blank" rel="noopener" class="text-link">KAIST Make Lab</a> under Prof. Andrea Bianchi, and before that I completed my double major at KAIST in Industrial Design and Computer Science.`,
  about: `I'm passionate about bringing traditional crafting and modern tech together and helping crafters digitize their processes and share their work in new ways. When I'm not researching or engineering, you'll find me crocheting, solving sudokus, bouldering, or traveling with my older sister.`,
  avatar: "images/profile-pic_square.jpg",
  cv: "files/cv.pdf",
  contact: {
    intro: "For collaborations, questions, or just to say hello, feel free to reach out to me through email at zofia.marciniak at inf.ethz.ch",
  },
  links: {
     github: { url: "https://github.com/zosiazamoyska", label: "GitHub" },
    linkedin: { url: "https://www.linkedin.com/in/zosia-marciniak-a2a7a9133", label: "LinkedIn" },
    scholar: { url: "https://scholar.google.com/citations?user=nPJl6dIAAAAJ", label: "Google Scholar" },
  },
};

const NEWS = [
  {
    date: "August 2026",
    title: "Started my PhD at ETH Zurich",
    body: "I began my PhD in the Department of Computer Science at ETH Zurich, advised by Prof. April Wang in the PEACH Lab.",
  },
  {
    date: "September 2025",
    title: "Presented StitchFlow at UIST 2025 in Busan",
    body: "Presented my first first-author paper and my master's thesis, StitchFlow, at UIST in Busan, South Korea!",
  },
  {
    date: "September 2025",
    title: "Became an Engineer at Samsung Electronics",
    body: "Officially started as an Engineer at Samsung Electronics!",
  },
];

const PUBLICATIONS = [
  {
    id: "stitchflow",
    title: "StitchFlow: Enabling In-Situ Creative Explorations of Crochet Patterns with Stitch Tracking and Process Sharing",
    authors: "Zofia Marciniak, Punn Lertjaturaphat, and Andrea Bianchi",
    venue: "UIST",
    year: 2025,
    url: "https://dl.acm.org/doi/full/10.1145/3746059.3747715",
    image: "images/StitchFlow_sq.png",
    featured: true,
    abstract: "Crochet resists automation, remaining a manual craft of improvisation. StitchFlow lets crocheters stay immersed while automatically documenting patterns, tracking progress, and sharing designs through motion sensing and a graphical interface.",
  },
  {
    id: "thermopixels",
    title: "3D Printing Locally Activated Visual-Displays Embedded in 3D Objects via Electrically Conductive and Thermochromic Materials",
    authors: "Kongpyung Moon, Zofia Marciniak, Ryo Suzuki, and Andrea Bianchi",
    venue: "CHI",
    year: 2024,
    url: "https://dl.acm.org/doi/10.1145/3613904.3642537",
    image: "images/thermopixels.png",
    featured: true,
    abstract: "ThermoPixels enables actively controlled thermochromic displays embedded in arbitrary 3D geometries, with software for designing flat, curved, and matrix displays.",
  },
  {
    id: "textureslicer-2024",
    title: "Decoupling Geometry from Surface Finish by Parameterizing Texture Directly in G-code for FDM Printing",
    authors: "Zofia Marciniak, Kongpyung Moon, and Andrea Bianchi",
    venue: "AODR",
    year: 2024,
    url: "https://aodr.org/_common/do.php?a=full&b=12&bidx=3672&aidx=40683",
    image: "images/textureslicer.png",
    featured: true,
    abstract: "Texture-Slicer applies texture patterns during slicing rather than modeling, keeping the 3D model unchanged while enabling tunable roughness through G-code modifications.",
  },
  {
    id: "textureslicer-2023",
    title: "3D Printing Slicer for Computational Texture Generation",
    authors: "Zofia Marciniak, Kongpyung Moon, and Andrea Bianchi",
    venue: "Korea HCI",
    year: 2023,
    url: "https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11229626",
    image: "images/prints.png",
    featured: false,
    abstract: "A novel workflow for 3D printing varied surface finishes without CAD texture modeling, by computationally generating G-code with embedded texture patterns.",
  },
  {
    id: "guidering",
    title: "Guide Ring: Bidirectional Finger-worn Haptic Actuator for Rich Haptic Feedback",
    authors: "Zofia Marciniak, Seo Young Oh, and Sang Ho Yoon",
    venue: "VRST (Poster)",
    year: 2022,
    url: "https://dl.acm.org/doi/10.1145/3562939.3565626",
    image: "images/guidering.GIF",
    featured: false,
    abstract: "A wearable haptic device using electromagnetic coils and permanent magnets to create guidance effects through magnetic attraction and repulsion.",
  },
  {
    id: "weather",
    title: "Understanding the impact of the Weather on Human Mobility via LTE Access Traces in Seoul Districts",
    authors: "Zofia Marciniak, Sumin Han, and Dongman Lee",
    venue: "Korea HCI",
    year: 2021,
    url: "https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE10530300",
    image: "images/weather_img.png",
    featured: false,
    abstract: "Exploring how weather conditions affect human activity in urban areas through mobile LTE access traces in Seoul.",
  },
];

const PROJECTS = [
  {
    id: "evergrow",
    title: "Evergrow: Investment Education Service",
    image: "images/evergrow_square.png",
    tags: ["UX/UI", "Finance", "iF Award"],
    featured: true,
    description: "Evergrow transforms stock investment into an engaging experience by visualizing portfolios as a growing forest, empowering beginners to build financial literacy.",
    team: "Jaeryung Chung, Jamie Ashley Dee, Minseo Bang, Zofia Marciniak, Eunseoo Oh",
  },
  {
    id: "dnd",
    title: "Do Not Disturb",
    image: "images/dnd-square.png",
    tags: ["UX", "Data Visualization"],
    featured: true,
    description: "An interface that promotes mindful phone usage, guides you to improve your phone habits, and helps you stay motivated through wise data visualization.",
    team: "Zhi Lin Yap, Siripon Sutthiwanna, Zofia Marciniak",
  },
  {
    id: "on-blog",
    title: "온 blog: Fulfilling creator's experience",
    image: "images/on_blog_square.png",
    tags: ["UX Design", "System Design"],
    featured: true,
    description: "Empowering Naver creators with a platform that strengthens their identity, fosters connections, and transforms their creative journey into a source of pride.",
    team: "Jian Jun, Jeongjae Lee, Hyerim Hwang, Zofia Marciniak, Adil Hassan Khan",
  },
  {
    id: "wheel",
    title: "Storytelling Wheel",
    image: "images/wheel.gif",
    tags: ["Media", "Interaction"],
    featured: true,
    description: "A phenakistiscope animation that reveals a hidden story with a UV flashlight, exploring layered narratives on three different levels.",
    team: "Solo project",
  },
  {
    id: "blocks",
    title: "Ear for blocks",
    image: "images/blocks_square.png",
    tags: ["Interactive", "Design"],
    featured: true,
    description: "An interactive toy that enables children to explore musical hearing — each block signifies a unique chord scanned and played by the device.",
    team: "Solo project",
  },
  {
    id: "alfresco",
    title: "Al Fresco",
    image: "images/alfresco-square.png",
    tags: ["Product Design", "For Humanity"],
    featured: true,
    description: "A terracotta-based natural cooling system using evaporation, designed for installation in public fountains to cool cities in summer heat.",
    team: "Jian Jun, Wonyoung Lee, Zofia Marciniak, Jeanyoon Choi, Luca Trevisani",
  },
  {
    id: "textureslicer-poster",
    title: "Poster for Texture Slicer",
    image: "images/textureslicer-poster-square.png",
    tags: ["Research", "Illustration"],
    featured: false,
    description: "A poster made during a difficult phase of the Texture Slicer project — playing in Illustrator helped restore passion and finish the paper.",
    team: "Solo project",
  },
  {
    id: "closet",
    title: "Out of the closet",
    image: "images/closet_square.jpg",
    tags: ["Graphic Design", "LGBTQIA+"],
    featured: false,
    description: "A small multiples graphic celebrating the vibrant diversity of the LGBTQIA+ community through cultural and fashion expressions.",
    team: "Solo project",
  },
  {
    id: "hanging",
    title: "Hanging In There",
    image: "images/hanging-in-there_square.png",
    tags: ["Illustration", "Personal"],
    featured: false,
    description: "A hand-drawn illustration exploring resilience — a girl holding onto a heart-shaped ring, trying to cover up the hole.",
    team: "Solo project",
  },
  {
    id: "love",
    title: "Love: Not For Sale",
    image: "images/love.png",
    tags: ["Personal", "Food"],
    featured: false,
    description: "A tribute to really delicious sandwiches my boyfriend cooked — sunny side up egg, ham, cheese, lettuce on roasted buns.",
    team: "Solo project",
  },
  {
    id: "goodmourning",
    title: "Good Mourning",
    image: "images/gm_artboard.png",
    tags: ["Personal Art"],
    featured: false,
    description: "An artboard inspired by the song 'good mourning' from my favourite Halsey album.",
    team: "Solo project",
  },
];

const FUN = [
  {
    id: "hat",
    title: "Pink Hat",
    type: "Crochet",
    year: 2022,
    images: ["fun/images/hat1.jpg", "fun/images/hat2.jpg"],
  },
  {
    id: "top",
    title: "Top",
    type: "Crochet",
    year: 2022,
    images: ["fun/images/top1.jpg", "fun/images/top2.jpg", "fun/images/top3.jpg"],
  },
  {
    id: "vest",
    title: "Crochet Ombree Vest",
    type: "Crochet",
    year: 2023,
    images: ["fun/images/vest1.jpg", "fun/images/vest2.jpg", "fun/images/vest3.jpg"],
  },
  {
    id: "color-set",
    title: "Bonnet and Wrist Warmers",
    type: "Crochet",
    year: 2024,
    images: ["fun/images/color_set.jpg", "fun/images/color_set2.jpg"],
  },
  {
    id: "color-vest",
    title: "Colorful Vest",
    type: "Crochet",
    year: 2024,
    images: ["fun/images/color_vest.jpg", "fun/images/color_vest1.jpg"],
  },
  {
    id: "punn-vest",
    title: "Vest for a friend",
    type: "Crochet",
    year: 2024,
    images: ["fun/images/punn_vest1.jpg", "fun/images/punn_vest2.jpg"],
    credit: "Pattern by day la hanh",
  },
  {
    id: "sweater-green",
    title: "Green Cat Sweater",
    type: "Crochet",
    year: 2025,
    images: ["fun/images/sweater_green.jpeg", "fun/images/sweater_green_1.jpeg", "fun/images/sweater_green_3.jpeg"],
  },
  {
    id: "sweater-blue",
    title: "Blue Sweater",
    type: "Tunisian Crochet",
    year: 2026,
    images: ["fun/images/sweater_blue.jpeg", "fun/images/sweater_blue_1.jpeg"],
  }
];
